In [1]:
import pandas as pd
movies=pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv')

In [2]:
movies.head()

,Movie_ID,Movie_Title,Movie_Genre,Movie_Language,Movie_Budget,Movie_Popularity,Movie_Release_Date,Movie_Revenue,Movie_Runtime,Movie_Vote,...,Movie_Homepage,Movie_Keywords,Movie_Overview,Movie_Production_House,Movie_Production_Country,Movie_Spoken_Language,Movie_Tagline,Movie_Cast,Movie_Crew,Movie_Director
0,1,Four Rooms,Crime Comedy,en,4000000,22.876230,09-12-1995,4300000,98.0,6.5,...,NaN,hotel new year's eve witch bet hotel room,It's Ted the Bellhop's first night on the job....,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,"[{'name': 'Allison Anders', 'gender': 1, 'depa...",Allison Anders
1,2,Star Wars,Adventure Action Science Fiction,en,11000000,126.393695,25-05-1977,775398007,121.0,8.1,...,http://www.starwars.com/films/star-wars-episod...,android galaxy hermit death star lightsaber,Princess Leia is captured and held hostage by ...,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,"[{'name': 'George Lucas', 'gender': 2, 'depart...",George Lucas
2,3,Finding Nemo,Animation Family,en,94000000,85.688789,30-05-2003,940335536,100.0,7.6,...,http://movies.disney.com/finding-nemo,father son relationship harbor underwater fish...,"Nemo, an adventurous young clownfish, is unexp...","[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
3,4,Forrest Gump,Comedy Drama Romance,en,55000000,138.133331,06-07-1994,677945399,142.0,8.2,...,NaN,vietnam veteran hippie mentally disabled runni...,A man with a low IQ has accomplished great thi...,"[{""name"": ""Paramount Pictures"", ""id"": 4}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,"[{'name': 'Alan Silvestri', 'gender': 2, 'depa...",Robert Zemeckis
4,5,American Beauty,Drama,en,15000000,80.878605,15-09-1999,356296601,122.0,7.9,...,http://www.dreamworks.com/ab/,male nudity female nudity adultery midlife cri...,"Lester Burnham, a depressed suburban father in...","[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes

In [3]:
movies.shape

(4760, 21)

In [4]:
movies.isnull().sum()

Movie_ID                       0
Movie_Title                    0
Movie_Genre                    0
Movie_Language                 0
Movie_Budget                   0
Movie_Popularity               0
Movie_Release_Date             0
Movie_Revenue                  0
Movie_Runtime                  2
Movie_Vote                     0
Movie_Vote_Count               0
Movie_Homepage              3061
Movie_Keywords               387
Movie_Overview                 3
Movie_Production_House         0
Movie_Production_Country       0
Movie_Spoken_Language          0
Movie_Tagline                818
Movie_Cast                    27
Movie_Crew                     0
Movie_Director                22
dtype: int64

In [5]:
movies.describe()

,Movie_ID,Movie_Budget,Movie_Popularity,Movie_Revenue,Movie_Runtime,Movie_Vote,Movie_Vote_Count
count,4760.000000,4.760000e+03,4760.000000,4.760000e+03,4758.000000,4760.000000,4760.000000
mean,2382.566387,2.920129e+07,21.599510,8.263743e+07,107.184111,6.113866,692.508403
std,1377.270159,4.075620e+07,31.887919,1.630554e+08,21.960332,1.141294,1235.007337
min,1.000000,0.000000e+00,0.000372,0.000000e+00,0.000000,0.000000,0.000000
25%,1190.750000,9.257500e+05,4.807074,0.000000e+00,94.000000,5.600000,55.000000
50%,2380.500000,1.500000e+07,13.119058,1.944716e+07,104.000000,6.200000,238.000000
75%,3572.250000,4.000000e+07,28.411929,9.341276e+07,118.000000,6.800000,740.250000
max,4788.000000,3.800000e+08,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [6]:
features=['Movie_Genre','Movie_Keywords','Movie_Tagline','Movie_Cast','Movie_Director']
for x in features:
    movies[x]=movies[x].fillna('')
movies['Combined_Features']=movies['Movie_Genre']+ ' ' + movies['Movie_Keywords'] + ' ' + movies['Movie_Tagline'] + ' ' + movies['Movie_Cast'] + ' ' + movies['Movie_Director']

In [7]:
movies

,Movie_ID,Movie_Title,Movie_Genre,Movie_Language,Movie_Budget,Movie_Popularity,Movie_Release_Date,Movie_Revenue,Movie_Runtime,Movie_Vote,...,Movie_Keywords,Movie_Overview,Movie_Production_House,Movie_Production_Country,Movie_Spoken_Language,Movie_Tagline,Movie_Cast,Movie_Crew,Movie_Director,Combined_Features
0,1,Four Rooms,Crime Comedy,en,4000000,22.876230,09-12-1995,4300000,98.0,6.5,...,hotel new year's eve witch bet hotel room,It's Ted the Bellhop's first night on the job....,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Twelve outrageous guests. Four scandalous requ...,Tim Roth Antonio Banderas Jennifer Beals Madon...,"[{'name': 'Allison Anders', 'gender': 1, 'depa...",Allison Anders,Crime Comedy hotel new year's eve witch bet ho...
1,2,Star Wars,Adventure Action Science Fiction,en,11000000,126.393695,25-05-1977,775398007,121.0,8.1,...,android galaxy hermit death star lightsaber,Princess Leia is captured and held hostage by ...,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","A long time ago in a galaxy far, far away...",Mark Hamill Harrison Ford Carrie Fisher Peter ...,"[{'name': 'George Lucas', 'gender': 2, 'depart...",George Lucas,Adventure Action Science Fiction android galax...
2,3,Finding Nemo,Animation Family,en,94000000,85.688789,30-05-2003,940335536,100.0,7.6,...,father son relationship harbor underwater fish...,"Nemo, an adventurous young clownfish, is unexp...","[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","There are 3.7 trillion fish in the ocean, they...",Albert Brooks Ellen DeGeneres Alexander Gould ...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton,Animation Family father son relationship harbo...
3,4,Forrest Gump,Comedy Drama Romance,en,55000000,138.133331,06-07-1994,677945399,142.0,8.2,...,vietnam veteran hippie mentally disabled runni...,A man with a low IQ has accomplished great thi...,"[{""name"": ""Paramount Pictures"", ""id"": 4}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","The world will never be the same, once you've ...",Tom Hanks Robin Wright Gary Sinise Mykelti Wil...,"[{'name': 'Alan Silvestri', 'gender': 2, 'depa...",Robert Zemeckis,Comedy Drama Romance vietnam veteran hippie me...
4,5,American Beauty,Drama,en,15000000,80.878605,15-09-1999,356296601,122.0,7.9,...,male nudity female nudity adultery midlife cri...,"Lester Burnham, a depressed suburban father in...","[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",Look closer.,Kevin Spacey Annette Bening Thora Birch Wes Be...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes,Drama male nudity female nudity adultery midli...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4755,4784,Midnight Cabaret,Horror,en,0,0.001389,01-01-1990,0,94.0,0.0,...,,A Broadway producer puts on a play with a Devi...,[],[],"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The hot spot where Satan's waitin'.,Lisa Hart Carroll Michael Des Barres Paul Drak...,"[{'name': 'Pece Dingo', 'gender': 0, 'departme...",Pece Dingo,Horror The hot spot where Satan's waitin'. Li...
4756,4785,Growing Up Smith,Comedy Family Drama,en,0,0.710870,03-02-2017,0,102.0,7.4,...,,"In 1979, an Indian family moves to America wit...",[],[],"[{""iso_639_1"": ""en"", ""name"": ""English""}]",It’s better to stand out than to fit in.,Roni Akurati Brighton Sharbino Jason Lee Anjul...,"[{'name': 'Frank Lotito', 'gender': 0, 'depart...",Frank Lotito,Comedy Family Drama It’s better to stand out ...
4757,4786,8 Days,Thriller Drama,en,0,0.015295,15-06-2014,0,90.0,0.0,...,christian film sex trafficking,"After sneaking to a party with her friends, 16...","[{""name"": ""After Eden Pictures"", ""id"": 85248}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...","[{""iso_639_1"": ""en"", ""name"": ""English""}]",She never knew it could happen to her...,Nicole Smolen Kim Baldwin Ariana Stephens Brys...,"[{'name': 'Jaco Booyens', 'gender': 0, 'depart...",Jaco Booyens,Thriller Drama christian film sex trafficking ...
4758,4787,Running Forever,Family,en,0,0.028756,27-10-2015,0,88.0,0.0,...,,After being estranged since her mother's death...,"[{""name"": ""New Kingdom Pictures"", ""id"": 41671}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",[],,,[],,Family
4759,4788,"To Be Frank, Sinatra at 100",Documentary,en,2,0.050625,12-12-2015,0,NaN,0.0,...,music actors legendary perfomer classic hollyw...,NaN,"[{""name"": ""Eyeline Entertainment"", ""id"": 60343}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",[],,Tony Oppedisano,"[{'name': 'Simon Napier-Bell', 'gender': 0, 'd...",Simon Napier-Bell,Documentary music actors legendary perfomer cl...

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(stop_words='english',max_features=5000)
feature_vector=vectorizer.fit_transform(movies['Combined_Features'])

In [9]:
print(feature_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 91643 stored elements and shape (4760, 5000)>
  Coords	Values
  (0, 987)	0.08136365828826038
  (0, 890)	0.0567834963436145
  (0, 2102)	0.31541591097908933
  (0, 3194)	0.22108007573089472
  (0, 4952)	0.32711729011079355
  (0, 1417)	0.3706898951063948
  (0, 4895)	0.16015968980306147
  (0, 389)	0.1967698066104338
  (0, 3810)	0.18382148629777284
  (0, 2701)	0.19048225295337298
  (0, 1090)	0.15049647743856415
  (0, 2309)	0.16742458430501572
  (0, 4861)	0.22143803757105399
  (0, 2642)	0.10872840505094206
  (0, 4480)	0.13142372733006938
  (0, 3827)	0.17969061536350603
  (0, 175)	0.16826575630626964
  (0, 293)	0.17392008849596097
  (0, 2280)	0.12291635152831967
  (0, 334)	0.21195720234454918
  (0, 2782)	0.2081946656676702
  (0, 2845)	0.17843809051719536
  (0, 4500)	0.18382148629777284
  (0, 105)	0.17969061536350603
  (0, 132)	0.20487587311364197
  :	:
  (4756, 1547)	0.4205357563589232
  (4756, 546)	0.44728625643668213
  (4757, 1252)	0.08434090700683997
  (4757, 4466)	0.11375178487494961
  (4757, 2462)	0.25978016797258996
  (4757, 2485)	0.34957007668998974
  (4757, 798)	0.2418409753306453
  (4757, 1526)	0.18563654629629636
  (4757, 3213)	0.2730462614521709
  (4757, 4017)	0.22223967267162922
  (4757, 1919)	0.32368375373449443
  (4757, 283)	0.28073607771924647
  (4757, 4261)	0.3604559766080455
  (4757, 4531)	0.3604559766080455
  (4757, 1641)	0.3604559766080455
  (4758, 1463)	1.0
  (4759, 3138)	0.23373401761236315
  (4759, 358)	0.31183513090717696
  (4759, 4505)	0.28875920801226895
  (4759, 1606)	0.28737103605780895
  (4759, 4108)	0.29546250305488414
  (4759, 1209)	0.2693094941068848
  (4759, 2071)	0.3886624687253099
  (4759, 831)	0.41380815529648635
  (4759, 2595)	0.44726040429818853

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(feature_vector)
print(similarity)
print('matrix shape: ',similarity.shape)

[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.09596117 0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.09596117 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]
matrix shape:  (4760, 4760)

In [11]:
movies.columns

Index(['Movie_ID', 'Movie_Title', 'Movie_Genre', 'Movie_Language',
       'Movie_Budget', 'Movie_Popularity', 'Movie_Release_Date',
       'Movie_Revenue', 'Movie_Runtime', 'Movie_Vote', 'Movie_Vote_Count',
       'Movie_Homepage', 'Movie_Keywords', 'Movie_Overview',
       'Movie_Production_House', 'Movie_Production_Country',
       'Movie_Spoken_Language', 'Movie_Tagline', 'Movie_Cast', 'Movie_Crew',
       'Movie_Director', 'Combined_Features'],
      dtype='str')

In [12]:
import difflib
list_of_all_titles=movies['Movie_Title'].tolist()
print(list_of_all_titles[:5])

['Four Rooms', 'Star Wars', 'Finding Nemo', 'Forrest Gump', 'American Beauty']

In [13]:
import difflib
movie_name='Iron Man'
find_closet_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print("closest match found: ",find_closet_match)
close_match=find_closet_match[0]
print("final selected movie is: ",close_match)

closest match found:  ['Iron Man', 'Iron Man 3', 'Iron Man 2']
final selected movie is:  Iron Man

In [16]:
import pickle
pickle.dump(movies.to_dict(),open('movie_dict.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))
print('Model and Data both are successfully packed')

Model and Data both are successfully packed